name: Test API
on:
  push:
    paths:
      - 'scripts/test-api.mjs'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Test
        env:
          REWAA_PASSWORD: ${{ secrets.REWAA_PASSWORD }}
        run: node scripts/test-api.mjs
